# Scenarios Configuration for LiDAR Beam loos
# =========================================================

# Baseline scenario: No Beam loos injected
normal_operation_outlier:
  params:
    outlier_percentage: 0.0
  duration: 1200
  runs: 0

# Low percentage
low_outlier_specular:
  params:
    outlier_percentage: 2.0
  duration: 1200
  runs: 4

# Medium  Percentage 
medium_outlier_specular:
  params:
    outlier_percentage: 4.0
  duration: 1200
  runs: 4

# High  Percentage 
high_outlier_specular:
  params:
    outlier_percentage: 6.0
  duration: 1200
  runs: 4
